ProyectoTienda/AppTienda/urls.py
from django.urls import path
from AppTienda import views


app_name = 'Tienda'
urlpatterns = [
    path('', views.index, name="Index"),
    path('categorias/', views.categorias, name="Categorias"),
    path('categorias/<str:categoria>', views.categoria, name="b_categoria"),
    path('acerca/', views.acerca, name="Acerca"),
    path('contacto/', views.contacto, name="Contacto"),
    path('nuevo/', views.nuevo, name="Nuevo"),
    path('buscar/', views.buscar, name="Buscar"),
    path('registro/', views.registrarse, name="registrarse"),
    path('logout/', views.logout, name="logout"),
    path('<int:prod_id>', views.ver_producto, name="VerProducto"),
    path('<int:prod_id>/editar/', views.editar_producto, name="EditarProducto"),
    #path('<int:prod_id>/editar/update', views.update_editar_producto, name="UpdateEditarProducto"),
    path('agregar/<int:prod_id>', views.agregar_producto, name="AgregarProducto"),
    path('carro/', views.ver_carro, name="VerCarro"),
    path('carro/limpiar', views.limpiar_carro, name="LimpiarCarro"),
    path('carro/restar/<int:prod_id>', views.restar_producto, name="RestarCarro"),
    path('eliminar/<int:prod_id>', views.eliminar_producto, name="EliminarProducto"),


]

ProyectoTienda/ProyectoTienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppTienda.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ProyectoTienda/AppTienda/models.py
from django.db import models

# Create your models here.
class CategoriaProd(models.Model):
    nombre= models.CharField(max_length=20)

    class Meta:
        verbose_name="CategoriaProd"
        verbose_name_plural="CategoriasProd"
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    titulo= models.CharField(max_length=50)
    imagen = models.ImageField(upload_to="AppTienda", null=True, blank=True)
    descripcion=models.CharField(max_length=150)
    precio = models.FloatField()
    categoria=models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)

    class Meta:
        verbose_name="Producto"
        verbose_name_plural="Productos"
    def __str__(self):
        return self.titulo

ProyectoTienda/AppTienda/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ContactForm(forms.Form):
    nombre = forms.CharField(label="Nombre", max_length=100, required=True)

    email = forms.EmailField(label="Email", required=True)
    mensaje = forms.CharField(widget=forms.Textarea, label="Mensaje")


class NuevoProductoForm(forms.Form):
    titulo = forms.CharField(label="Nombre", max_length=50, required=True)
    descripcion = forms.CharField(widget=forms.Textarea, label="Descripcion")
    imagen = forms.ImageField()
    

#Form creado para extraer la imagen y que sirva el Upload_to
#Sin el form no se guardaba en la carpeta media por lo que al querer mostrar no habia imagen
class ImagenUploadForm(forms.Form):
    
    imagen = forms.ImageField()


class RegistroForm(UserCreationForm):
    username = forms.CharField(
        label='Usuario', widget=forms.TextInput(attrs={'class': 'usuario'}), max_length=150, required=True, help_text='Requerido. 150 caracteres o menos. Letras, dígitos y @ /. / + / - / _ solamente.')
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput(), max_length=30, required=True, help_text='Requerido. Al menos 8 caracteres y no pueden ser todos numeros.')
    password2 = forms.CharField(
        label='Repetir Password', widget=forms.PasswordInput(), max_length=30, required=True, help_text='Requerido. Ingrese la misma contraseña que antes, para verificación.')
    first_name = forms.CharField(
        label='Nombre', widget=forms.TextInput(attrs={'class': 'nombre'}), max_length=30, required=False, help_text='Opcional.')
    last_name = forms.CharField(
        label='Apellido', widget=forms.TextInput(attrs={'class': 'apellido'}), max_length=30, required=False, help_text='Opcional.')
    email = forms.EmailField(
        label='Email', widget=forms.TextInput(attrs={'class': 'email'}), max_length=254, required=True, help_text='Se requiere una direccion de email valida.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

ProyectoTienda/AppTienda/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from .models import Producto, CategoriaProd
from .forms import ContactForm, ImagenUploadForm,RegistroForm
from django.core.mail import EmailMessage
from django.conf import settings
from django.contrib.auth import logout
from .carro import Carro
from django.contrib.auth.decorators import login_required, permission_required
# Create your views here.
def index(request):
    productos=Producto.objects.all()
    return render(request,"AppTienda/index.html",{ "productos": productos })

def categorias(request):
    cat = CategoriaProd.objects.all()
    return render(request, "AppTienda/categorias.html", {"categorias": cat})

def categoria(request,categoria):
    cat = CategoriaProd.objects.get(nombre=categoria)
    productos= Producto.objects.filter(categoria=cat.id)
    
    #cat = CategoriaProd.objects.all()
    return render(request, "AppTienda/categoria.html", {"productos": productos, "categoria": cat})

def acerca(request):
    return render(request, "AppTienda/acerca.html",)

def buscar(request):
    if request.method == "POST":
        texto = request.POST.get("buscar")
        productos=Producto.objects.filter(titulo__contains=texto)
        return render(request,"AppTienda/buscar.html",{"productos":productos})


def contacto(request):
    form = ContactForm()

    if request.method == "POST":
        form = ContactForm(data=request.POST)
        if form.is_valid():
            nombre = request.POST.get("nombre")
            email = request.POST.get("email")
            mensaje = request.POST.get("mensaje")

            #send_mail(nombre,contenido,) #otra forma
            em = EmailMessage("Mensaje desde App",
                              "El usuario {}, email: {}, escribe: \n\n {}".format(nombre, email, mensaje),
                              "", [settings.EMAIL_HOST_USER], reply_to=[email])

            try:
                em.send()
                return redirect("/contacto/?valido")
            except:
                return redirect("/contacto/?error")

    return render(request, "AppTienda/contacto.html", {"formulario": form})

@permission_required('Tienda.add_producto')
def nuevo(request):
    cat = CategoriaProd.objects.all()
    #Incluido para poder tener upload_to al momento de guardar la imagen
    #Se puede mejorar
    form = ImagenUploadForm(request.POST, request.FILES)
    if form.is_valid():
        img=form.cleaned_data['imagen']
    ########################################################
    ########################################################
    if request.method=="POST":

    
        titulo=request.POST.get("titulo")
        descripcion=request.POST.get("descripcion")
        categoria=request.POST.get("categoria")
        imagen=img  #request.POST.get("imagen")
        precio=request.POST.get("precio")

        bcat = CategoriaProd.objects.get(nombre=categoria)

        nuevo_prod=Producto(titulo=titulo,imagen=imagen,descripcion=descripcion,precio=precio,categoria=bcat)

        try:
            nuevo_prod.save()
            return redirect("/nuevo/?valido")
        except:
            return redirect("/nuevo/?error")        



    return render(request,"AppTienda/nuevo.html",{"categorias": cat})


def ver_producto(request,prod_id):
    
    producto= Producto.objects.get(id=prod_id)
    
    #cat = CategoriaProd.objects.all()
    return render(request, "AppTienda/ver_producto.html", {"producto": producto,})

@permission_required('Tienda.change_producto')
@permission_required('Tienda.delete_producto')
def editar_producto(request,prod_id):
    cat = CategoriaProd.objects.all()
    producto= Producto.objects.get(id=prod_id)
    list_cat=[]
    for c in cat:
        list_cat.append(c)

    if request.method=="POST":
        form = ImagenUploadForm(request.POST, request.FILES)
        if form.is_valid():
            img=form.cleaned_data['imagen']

        titulo=request.POST.get("titulo")
        descripcion=request.POST.get("descripcion")
        categoria=request.POST.get("categoria")
        imagen=img  #request.POST.get("imagen")
        precio=float(request.POST.get("precio"))

        bcat = CategoriaProd.objects.get(nombre=categoria)
        update_prod=Producto.objects.get(id=request.POST.get("id"))
        update_prod.titulo=titulo
        update_prod.descripcion=descripcion
        update_prod.categoria=bcat
        update_prod.precio=precio
        update_prod.imagen=imagen

        #nuevo_prod=Producto(titulo=titulo,imagen=imagen,descripcion=descripcion,precio=precio,categoria=bcat)

        try:
            id=request.POST.get("id")
            update_prod.save()
            #return HttpResponseRedirect(reverse("Tienda:EditarProducto", args=(producto.id,)))
            return redirect(f"/{id}/editar/?valido")
        except:
            return redirect(f"/{id}/editar/?error")
    return render(request, "AppTienda/editar_producto.html", {"producto": producto,"categorias": list_cat})

def eliminar_producto(request,prod_id):
    producto= Producto.objects.get(id=prod_id)
    try:
        producto.delete()
        return redirect("/")
    except:
        print("error")
        return redirect("/")
      







def registrarse(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():

            try:
                form.save()    
                return redirect("/accounts/login/?valido") 
            except:
                return redirect("/accounts/login/?error")     
            #return HttpResponseRedirect(reverse('login'))
    else:
        form = RegistroForm()
    return render(request, 'registration/registro.html', {
        'form': form
        })

def logout(request):
    logout(request)
    return redirect("/accounts/login/")

######################################
###Vistas para el carrito de compra###
######################################
@login_required
def agregar_producto(request,prod_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=prod_id)
    carro.agregar(producto=producto)
    #print(carro)
    #print(producto.precio)

    return redirect("/")
"""
def eliminar_producto(request,prod_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=prod_id)
    carro.eliminar(producto=producto)

    return redirect("tienda")
"""
def restar_producto(request,prod_id):
    carro=Carro(request)
    producto=Producto.objects.get(id=prod_id)
    carro.restar_producto(producto=producto)
    return redirect("/carro")

def limpiar_carro(request):
    carro=Carro(request)
    carro.limpiar_carro()
    return redirect("/")

    

def ver_carro(request):
    carro= request.session.get("carro")
    #print(carro)
    return render(request, "AppTienda/ver_carro.html", {"carro": carro,})

ProyectoTienda/AppTienda/templates/AppTienda/acerca.html
{% extends 'AppTienda/base.html' %}
{% load static %}
{% block title %}Tienda - Acerca De{% endblock title %}


{% block content %}
<h1>Acerca de Nosotros</h1>

<h2> JAGUARETE KAA S.A</h2>

<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptas necessitatibus expedita soluta vitae magni, perferendis, dolores cupiditate inventore ratione temporibus quo voluptatum porro impedit reprehenderit, ab officiis laudantium laborum a.</p>

{% endblock content %}

ProyectoTienda/AppTienda/templates/AppTienda/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="{% static 'AppTienda/css/estilos.css' %}" rel="stylesheet">

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>


    <div id="login">
    <ul>
    {% if request.user.is_authenticated %}
            <li>Hola {{user.username}} </li>
            <li><a href="{% url 'Tienda:VerCarro' %}">Ver Carrito</a></li>
            <li><a href="{% url 'logout' %}">Salir</a></li>
            
            

    {% else %}


        
            <li> <a href="{% url 'login' %}">Login</a> </li>
            <li><a href="{% url 'Tienda:registrarse' %}">Registrarse</a> </li>
            
       
    {% endif%}
     </ul>
    </div>
    <header>
        <h1>Tienda</h1>
    </header>

    <nav>
        <ul>
            <li><a href="{% url 'Tienda:Index' %}">Home</a></li>
            <li><a href="{% url 'Tienda:Categorias' %}">Categorias</a></li>
            <li><a href="{% url 'Tienda:Acerca' %}">Acerca De</a></li>
            <li><a href="{% url 'Tienda:Contacto' %}">Contacto</a></li>
            {% if request.user.is_authenticated %}
                {% if perms.Tienda.add_producto %}
                    <li><a href="{% url 'Tienda:Nuevo' %}">Nuevo</a></li>
                {% endif%}
            {% endif%}
        </ul>
        <form id="form_buscar" action="{% url 'Tienda:Buscar' %}" method="POST"> {% csrf_token %}
            <input type="text" name="buscar" placeholder="buscar...">
            

            <input type="submit" value="Buscar">
        </form>
        
    </nav>
    <section>
    {% block content %} {% endblock content %}
    </section>
    <footer>
        <p>Realizado por José Rojas - joseangel038@gmail.com</p>
        <p>&copy; Sistema de Tienda y carrito de compras para PoloTic 2021</p>

    </footer>

</body>
</html>

ProyectoTienda/AppTienda/templates/AppTienda/buscar.html
{% extends 'AppTienda/base.html' %}
{% load static %}
{% block title %}Tienda - Home{% endblock title %}


{% block content %}

{% for producto in productos %}

<div class="card">
    <img src="{{producto.imagen.url}}" alt="{{ producto.titulo }}" style="width:50%">
    <h1><a href="
    {% if request.user.is_authenticated %}
                {% if perms.Tienda.change_producto or perms.Tienda.delete_producto  %}
                    {% url 'Tienda:EditarProducto' producto.id %}
                {% else %}
                    {% url 'Tienda:VerProducto' producto.id %}
                {% endif%}
    {% else %}
        {% url 'Tienda:VerProducto' producto.id %}
    {% endif%}
    
    "> 
    {{ producto.titulo }} </a></h1>
    <p class="price">${{ producto.precio }}</p>
    <p>{{ producto.descripcion }}</p>
    <button role="link" onclick="window.location.href='{% url 'Tienda:AgregarProducto' producto.id  %}';">Agregar al carrito</button>
    </div>


{% endfor %}






{% endblock content %}

ProyectoTienda/AppTienda/templates/AppTienda/categoria.html
{% extends 'AppTienda/base.html' %}
{% load static %}
{% block title %}Tienda - Categoria{% endblock title %}


{% block content %}

<h1>{{ categoria.nombre }}</h1>
<ul>

{% for producto in productos %}
    <div class="card">
    <img src="{{producto.imagen.url}}" alt="{{ producto.titulo }}" style="width:50%">
    <h1><a href="
    {% if request.user.is_authenticated %}
                {% if perms.Tienda.change_producto or perms.Tienda.delete_producto  %}
                    {% url 'Tienda:EditarProducto' producto.id %}
                {% else %}
                    {% url 'Tienda:VerProducto' producto.id %}
                {% endif%}
    {% else %}
        {% url 'Tienda:VerProducto' producto.id %}
    {% endif%}
    
    "> 
    {{ producto.titulo }} </a></h1>
    <p class="price">${{ producto.precio }}</p>
    <p>{{ producto.descripcion }}</p>
    <button role="link" onclick="window.location.href='{% url 'Tienda:AgregarProducto' producto.id  %}';">Agregar al carrito</button>
    </div>
{% empty %}
    <p>Nada que mostrar</p>
{% endfor %}
</ul>
{% endblock content %}

ProyectoTienda/AppTienda/templates/AppTienda/categorias.html
{% extends 'AppTienda/base.html' %}
{% load static %}
{% block title %}Tienda - Categorias{% endblock title %}


{% block content %}

<h1>Categorias</h1>
<ul>

{% for categoria in categorias %}
    <li> <a href="{% url 'Tienda:b_categoria' categoria.nombre %}">{{ categoria.nombre }}</a>  </li>
{% endfor %}
</ul>
{% endblock content %}

ProyectoTienda/AppTienda/templates/AppTienda/contacto.html
{% extends 'AppTienda/base.html' %}
{% load static %}
{% block title %}Tienda - Contacto{% endblock title %}


{% block content %}
<div class="formulario">

    {% if "valido" in request.GET %}
        <p>Enviado Correctamente</p>

    {% endif %}

    {% if "error" in request.GET %}
        <p>Ocurrio un error al enviar</p>

    {% endif %}

    <form action="" method="POST"> {% csrf_token %}
    <table>
    {{ formulario.as_table }}
    </table>

    <input type="submit" value="Enviar">


    </form>
</div>
{% endblock content %}

ProyectoTienda/AppTienda/templates/AppTienda/editar_producto.html
{% extends 'AppTienda/base.html' %}
{% load static %}
{% block title %}Tienda - Producto{% endblock title %}


{% block content %}
    {% if "valido" in request.GET %}
        <p>Actualizado Correctamente</p>
    
    {% endif %}

    {% if "error" in request.GET %}
        <p>Ocurrio un error al Actualizar</p>
    
    {% endif %}

    <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}

    <table>
   <tr><th><label for="id">Id: </label></th><td><input type="text" name="id" id="id" value="{{producto.id}}" readonly></td></tr>
   <tr><th><label for="titulo">Titulo: </label></th><td><input type="text" name="titulo" id="titulo" value="{{producto.titulo}}"></td></tr>

   <tr><th><label for="descripcion">Descripción: </label></th><td><textarea name="descripcion" id="descripcion" cols="25" rows="10" value="">{{producto.descripcion}}</textarea></td></tr>

   <tr><th><label for="categoria">Categoria: </label></th><td>   
        <select name="categoria" id="categoria" >

      {% for categoria in categorias %}
        
        {% if categoria == producto.categoria  %}
            <option value="{{ categoria.nombre }}" selected="selected">{{ categoria.nombre }}</option>
        {% else %}
             <option value="{{ categoria.nombre }}">{{categoria.nombre}}</option>
        {% endif %}
      {% endfor %}

      </select>
      </td></tr>
   
    <tr><th><label for="imagen">Imagen: </label></th><td> <input type="file" id="imagen" name="imagen" accept="image/png, image/jpeg">  </td></tr>

      <tr><th><label for="precio">Precio: </label></th><td><input type="text" name="precio" id="precio" value="{{producto.precio}}"> </td></tr>

    <tr><th><input type="submit" value="Editar"></th><td></td></tr>
    </table>


     </form>
     <button onclick="window.location.href='{% url 'Tienda:EliminarProducto' producto.id  %}';">Eliminar</button>
<h1>{{producto.titulo}}</h1>

<p>{{ producto.categoria }} - ${{ producto.precio }}</p>

<p>{{ producto.descripcion }}</p>

<img id="ver_prod" class="" src="{{producto.imagen.url}}" alt="" style="width: 50%;">

{% endblock content %}

ProyectoTienda/AppTienda/templates/AppTienda/index.html
{% extends 'AppTienda/base.html' %}
{% load static %}
{% block title %}Tienda - Home{% endblock title %}


{% block content %}

<h1>Productos</h1>


{% for producto in productos %}
    

    <div class="card">
    <img src="{{producto.imagen.url}}" alt="{{ producto.titulo }}" style="width:50%">
    <h1><a href="
    {% if request.user.is_authenticated %}
                {% if perms.Tienda.change_producto or perms.Tienda.delete_producto  %}
                    {% url 'Tienda:EditarProducto' producto.id %}
                {% else %}
                    {% url 'Tienda:VerProducto' producto.id %}
                {% endif%}
    {% else %}
        {% url 'Tienda:VerProducto' producto.id %}
    {% endif%}
    
    "> 
    {{ producto.titulo }} </a></h1>
    <p class="price">${{ producto.precio }}</p>
    <p>{{ producto.descripcion }}</p>
    <button role="link" onclick="window.location.href='{% url 'Tienda:AgregarProducto' producto.id  %}';">Agregar al carrito</button>
    </div>



{% endfor %}

{% endblock content %}

ProyectoTienda/AppTienda/templates/AppTienda/nuevo.html
{% extends 'AppTienda/base.html' %}
{% load static %}
{% block title %}Tienda - Nuevo Producto{% endblock title %}

{% block content %}

   {% if "valido" in request.GET %}
        <p>Creado Correctamente</p>
    
    {% endif %}

    {% if "error" in request.GET %}
        <p>Ocurrio un error al crear</p>
    
    {% endif %}

 <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}

   <table>
   <tr><th><label for="titulo">Titulo: </label></th><td><input type="text" name="titulo" id="titulo"></td></tr>

   <tr><th><label for="descripcion">Descripción: </label></th><td><textarea name="descripcion" id="descripcion" cols="30" rows="10"></textarea></td></tr>

   <tr><th><label for="categoria">Categoria: </label></th><td>

      <select name="categoria" id="categoria">

      {% for categoria in categorias %}
    
      <option value="{{ categoria.nombre }}">{{ categoria.nombre }}</option>
      {% endfor %}

      </select></td></tr>
   
    <tr><th><label for="imagen">Imagen: </label></th><td> <input type="file" id="imagen" name="imagen" accept="image/png, image/jpeg">  </td></tr>

      <tr><th><label for="precio">Precio: </label></th><td><input type="text" name="precio" id="precio"> </td></tr>

    <tr><th><input type="submit" value="Crear"></th></tr>
    </table>


 </form>


{% endblock content %}

ProyectoTienda/AppTienda/templates/AppTienda/ver_carro.html
{% extends 'AppTienda/base.html' %}
{% load static %}
{% block title %}Tienda - Carrito{% endblock title %}


{% block content %}

<h1>Productos en Carrito de compras</h1>

<table id="carro">
<tr>
    <th>Producto</th>
    <th>Cantidad</th>
    <th>Precio</th>
    <th>Restar</th>
</tr>

{% for id, valor in carro.items %}
     <tr>
     <td>{{ valor.titulo }}</td>
     <td>{{ valor.cantidad }}</td>
     <td>${{ valor.precio }}</td>
     <td><a href="{% url 'Tienda:RestarCarro' valor.producto_id %}">X</a></td>
     </tr>    
    
    {% endfor %}

</table>
<a href="{% url 'Tienda:LimpiarCarro' %}">Vaciar carrito</a>

{% endblock content %}

ProyectoTienda/AppTienda/templates/AppTienda/ver_producto.html
{% extends 'AppTienda/base.html' %}
{% load static %}
{% block title %}Tienda - Producto{% endblock title %}


{% block content %}

<h1>{{producto.titulo}}</h1>

<p>{{ producto.categoria }} - ${{ producto.precio }}</p>

<p>{{ producto.descripcion }}</p>

<img id="ver_prod" class="" src="{{producto.imagen.url}}" alt="" style="width: 50%;">

{% endblock content %}

ProyectoTienda/AppTienda/templates/AppTienda/ver_producto2.html
{% extends 'AppTienda/base.html' %}
{% load static %}
{% block title %}Tienda - Producto{% endblock title %}


{% block content %}
{% for producto in productos %}
<h1>{{producto.titulo}}</h1>

<p>{{ producto.categoria }} - ${{ producto.precio }}</p>

<p>{{ producto.descripcion }}</p>

<img id="ver_prod" class="" src="{{producto.imagen.url}}" alt="" style="width: 50%;">

{% endfor %}

{% endblock content %}